spring:
  application:
    name: studentTaskTracker

  datasource:
    url: jdbc:postgresql://localhost:5432/studentTaskTracker
    username: user
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardIml
    show-sql: true

    properties:
      hibernate:
        format_sql: true

#  security:
#    user:
#      name: ${SEC_USER_NAME:admin@mail.ru}
#      password: ${SEC_USER_PASSWORD:password}
#      roles: ADMIN

  jackson:
    mapper:
      accept-case-insensitive-enums: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

  show-actuator: true

server:
  port: 8080

jwt:
  key: ${JWT_SIGNING_KEY:9ab3fee80daeaf6f8c80d420be7ad1e29a6fef1cde8efafd8a551789c479c2b6}
  access-token-expiration: 36000000
  refresh-token-expiration: 2592000000
